language: java
script: asdf plugin-test ballerina https://github.com/savoisn/asdf-ballerina.git "ballerina --version"
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
